# Encoding:: utf-8
#
# (c) 2014, Ross Timson <ross@rosstimson.com>
#
# Ansible Playbook:: rosstimson-workstation
# License:: WTFPL
#

---
- name: Enable ipv4 forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Install Docker package
  yum: name=docker-io state=present

- name: Start/Enable Docker service
  service: name=docker state=started enabled=yes

- name: Append 'rosstimson' user to 'docker' group
  user: name=rosstimson groups=docker append=yes
